name: 勢いだけでやるページ on GitHub
title: 勢いだけでやるページ on GitHub
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-cayman

future: false           # 未来日付の投稿を公開しない
timezone: Asia/Tokyo    # 日付の基準となるタイムゾーンを指定

collections:
    feature:
        output: true

#cayman theme setting
show_downloads: false